language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev
  - sudo apt-get install -y hdf5-tools
matrix:
  - install: "python setup.py install"
  - install: "pip install picopore"
  - install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --add channels conda-forge
    - conda config --add channels defaults
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda install picopore -c bioconda -c conda-forge
# # command to run tests
script: python test/test.py
